#pragma once
#include <sstream>
#include <string>


inline std::string getTaskName(int type) {
  switch (type) {
  case 0:
    return "NULL_TASK";
  case 1:
    return "MOVE_ON_FREE_WILL";
  case 2:
    return "BUILD";
  case 3:
    return "PICKUP";
  case 4:
    return "MELEE_ATTACK";
  case 5:
    return "FOCUSED_MELEE_ATTACK";
  case 6:
    return "EQUIP_WEAPON";
  case 7:
    return "UNEQUIP_WEAPON";
  case 8:
    return "FIND_WEAPON";
  case 9:
    return "CHOOSE_ENEMY_AND_ATTACK";
  case 10:
    return "CHOOSE_ATTACKER_OF_ALLY";
  case 11:
    return "ATTACK_CHARACTERS_ATTACKER";
  case 12:
    return "PLAYER_TALK_TO";
  case 13:
    return "ATTACK_ATTACKERS_OF";
  case 14:
    return "IDLE";
  case 15:
    return "PROTECT_ALLIES";
  case 16:
    return "ATTACK_ENEMIES";
  case 17:
    return "PROTECTION";
  case 18:
    return "RAID_TOWN";
  case 19:
    return "GO_HOMEBUILDING";
  case 20:
    return "STAND_AT_SHOPKEEPER_NODE";
  case 21:
    return "ATTACK_ENEMIES_AND_NEUTRALS";
  case 22:
    return "PATROL";
  case 23:
    return "ATTACK_TOWN";
  case 24:
    return "WANDERER";
  case 25:
    return "FIRST_AID_ORDER";
  case 26:
    return "LOOT_TARGET";
  case 27:
    return "CROUCH";
  case 28:
    return "STAND_UP";
  case 29:
    return "MOVE_CUS_ORDERED";
  case 30:
    return "HOLD_POSITION";
  case 31:
    return "STAY_CLOSE_TO_TARGET";
  case 32:
    return "SELF_PRESERVATION";
  case 33:
    return "QUELL_AGGRESSION";
  case 34:
    return "ATTACK_TROUBLE_MAKERS";
  case 35:
    return "RUN_AWAY";
  case 36:
    return "PATROL_TOWN";
  case 37:
    return "WANDER_TOWN";
  case 38:
    return "STAND_AT_GUARD_NODE_HOMEBUILDING_IN_OUT";
  case 39:
    return "WANDERING_TRADER";
  case 40:
    return "GET_NEAR_TO";
  case 41:
    return "ATTACK_ENEMIES_OF_MY_SLAVEMASTER";
  case 42:
    return "NOT_BE_UNARMED";
  case 43:
    return "STAY_IN_HOME";
  case 44:
    return "FOLLOW_PLAYER_ORDER";
  case 45:
    return "BODYGUARD";
  case 46:
    return "CHASE";
  case 47:
    return "STAND_AT_GENERAL_NODE";
  case 48:
    return "STAND_AT_DEFENSIVE_NODE";
  case 49:
    return "STAND_AT_BUILDING_GUARD_NODE";
  case 50:
    return "STAND_AT_BUILDING_DEFENSIVE_NODE";
  case 51:
    return "STAND_AT_NODE";
  case 52:
    return "GET_UP_STAY_DOWN_THOUGH";
  case 53:
    return "TRAVEL_TO_TARGET_TOWN";
  case 54:
    return "REST";
  case 55:
    return "RECRUIT_AT_JOBCENTER";
  case 56:
    return "SWITCH_FOLLOW_ME_MODE_ON";
  case 57:
    return "JOB_REPAIR_ROBOT";
  case 58:
    return "JOB_MEDIC";
  case 59:
    return "GET_READY_FOR_ACTION";
  case 60:
    return "FIRST_AID_ROBOT";
  case 61:
    return "UNPROVOKED_FOCUSED_MELEE_ATTACK";
  case 62:
    return "STAND_STILL";
  case 63:
    return "SQUAD_WAIT_FOR_ME";
  case 64:
    return "MAKE_TARGET_STAND_STILL";
  case 65:
    return "GET_UP_STAND_UP";
  case 66:
    return "FORCE_GET_UP";
  case 67:
    return "MOVE_ON_FREE_WILL_FAST";
  case 68:
    return "LIFT_PERSON";
  case 69:
    return "PUT_DOWN_OBJECT";
  case 70:
    return "PUT_DOWN_CHARACTER_IN_BED";
  case 71:
    return "ADD_MATERIALS_TO_BUILDING";
  case 72:
    return "OPEN_DOOR";
  case 73:
    return "CLOSE_DOOR";
  case 74:
    return "OPEN_DOOR_HERE";
  case 75:
    return "CLOSE_DOOR_HERE";
  case 76:
    return "PICK_LOCK";
  case 77:
    return "LOCK_DOOR";
  case 78:
    return "UNLOCK_DOOR";
  case 79:
    return "LOCK_DOOR_HERE";
  case 80:
    return "UNLOCK_DOOR_HERE";
  case 81:
    return "BASH_DOOR";
  case 82:
    return "MOVE_TO_BUILDING_DOOR";
  case 83:
    return "MOVE_TO_CURRENT_LOCATION_BUILDING_DOOR";
  case 84:
    return "OPEN_DOOR_FOR_CURRENT_LOCATION";
  case 85:
    return "OPEN_DOOR_FOR_DESTINATION";
  case 86:
    return "OPEN_UP_SHOP_DOORS";
  case 87:
    return "OPERATE_MACHINERY";
  case 88:
    return "DELIVER_RESOURCES";
  case 89:
    return "JOB_KEEP_EVERYTHING_RUNNING";
  case 90:
    return "UNJAM_ALL_MACHINES";
  case 91:
    return "UNJAM_MACHINE";
  case 92:
    return "COLLECT_OUTPUT_RESOURCE";
  case 93:
    return "FILL_MACHINE";
  case 94:
    return "WANT_TO_FILL_MACHINE";
  case 95:
    return "REPAIR";
  case 96:
    return "DISMANTLE";
  case 97:
    return "USE_TRAINING_DUMMY";
  case 98:
    return "USE_BED";
  case 99:
    return "PUT_SOMEONE_IN_BED";
  case 100:
    return "GET_PUT_IN_BED";
  case 101:
    return "DEFEAT_SQUAD";
  case 102:
    return "SEEK_AND_TALK_AND_SEND_SIGNAL";
  case 103:
    return "MAKE_ANNOUNCEMENT";
  case 104:
    return "ALWAYS_IMPOSSIBLE_TASK";
  case 105:
    return "FIND_AND_RESCUE";
  case 106:
    return "FIND_BED_AND_PUT_IN";
  case 107:
    return "USE_CAGE";
  case 108:
    return "PUT_IN_CAGE";
  case 109:
    return "KNOCKOUT_PRISONER";
  case 110:
    return "RELEASE_PRISONER";
  case 111:
    return "BREAKOUT_PRISONER";
  case 112:
    return "FIND_CAGE_AND_PUT_IN";
  case 113:
    return "EMPTY_MACHINE_OUTPUTS";
  case 114:
    return "GET_RID_OF_RESOURCES_IN_MY_INVENTORY";
  case 115:
    return "FIND_SOME_BUILDING_MATERIALS";
  case 116:
    return "GET_OUT_OF_BED";
  case 117:
    return "FIND_A_SHOP";
  case 118:
    return "SHOPPING";
  case 119:
    return "BUY_SHIT";
  case 120:
    return "MOVE_INSIDE_BUILDING";
  case 121:
    return "MOVE_TO_FORTIFICATION_GATE";
  case 122:
    return "OPEN_FORTIFICATION_GATE";
  case 123:
    return "BASH_GATE";
  case 124:
    return "OPERATE_STORAGE";
  case 125:
    return "JOB_BUILDER";
  case 126:
    return "TALKTO_NEAREST_PLAYER_CHARACTER";
  case 127:
    return "RUN_AWAY_HOMETOWN";
  case 128:
    return "RETREAT_HOMETOWN";
  case 129:
    return "MAKE_ANNOUNCEMENT_FAST";
  case 130:
    return "TRAVEL_TO_TARGET_TOWN_FAST";
  case 131:
    return "LOOT_FOOD_AND_STUFF";
  case 132:
    return "FIND_AND_KIDNAP";
  case 133:
    return "GET_OUT_OF_CAGE_LEGIT";
  case 134:
    return "KILL_CAGE_OCCUPANT";
  case 135:
    return "KILL_A_RANDOM_CAGE_OCCUPANT";
  case 136:
    return "FEED_CORPSE_INTO_MACHINE";
  case 137:
    return "DEAD_GUYS_GO_IN_THE_POT";
  case 138:
    return "FIND_A_DEAD_GUY";
  case 139:
    return "EAT_A_RANDOM_CAGE_OCCUPANT";
  case 140:
    return "UNLOCK_DOOR_PLAYER_ORDER";
  case 141:
    return "FOLLOW_SQUADLEADER";
  case 142:
    return "FIND_AND_RESCUE_LEADER";
  case 143:
    return "PROTECT_OWN_SQUAD";
  case 144:
    return "TERRITORIAL_AGGRESSION_BUT_DONT_LEAVE_HOME";
  case 145:
    return "GET_RE_EQUIPPED";
  case 146:
    return "USE_TURRET";
  case 147:
    return "STUMBLE_TASK_FORCED";
  case 148:
    return "FIND_AND_RESCUE_IF_THERES_BEDS";
  case 149:
    return "MAN_A_TURRET";
  case 150:
    return "PROSPECTING";
  case 151:
    return "EMPTYING_MACHINE";
  case 152:
    return "OPERATE_AUTOMATIC_MACHINERY";
  case 153:
    return "GO_HOME_AND_GO_TO_BED";
  case 154:
    return "GO_TO_THE_BAR_AND_DRINK";
  case 155:
    return "LOCK_ALL_MY_DOORS";
  case 156:
    return "ENTER_BUILDING";
  case 157:
    return "STAND_AT_GUARD_NODE_HOMETOWN_OUTSIDE";
  case 158:
    return "SHOO_STRANGERS_OUT_OF_MY_BUILDING";
  case 159:
    return "SEND_DIALOGUE_SIGNAL";
  case 160:
    return "SEND_DIALOGUE_SIGNAL_REPEAT";
  case 161:
    return "SEND_DIALOGUE_SIGNAL_WITHOUT_MOVING";
  case 162:
    return "LOCK_DOOR_FROM_INSIDE";
  case 163:
    return "MOVE_TO_BUILDING_DOOR_INSIDEPOS";
  case 164:
    return "FOLLOW_WHILE_TALKING";
  case 165:
    return "TOWN_STALKER";
  case 166:
    return "CHAIN_TARGET";
  case 167:
    return "CAPTURE_NEW_SLAVES";
  case 168:
    return "CARRY_WOUNDED_SLAVES";
  case 169:
    return "PUT_DOWN_CARRIED_DUDE_IF_THEY_CAN_WALK";
  case 170:
    return "LIFT_OBJECT_BUT_HEAL_FIRST";
  case 171:
    return "FOLLOW_SLAVEMASTER";
  case 172:
    return "SLAVE_GET_IN_MY_MASTERS_CAGE";
  case 173:
    return "GATHER_SLAVES_FROM_CAGES";
  case 174:
    return "GET_SLAVE";
  case 175:
    return "SLEEP_ON_FLOOR";
  case 176:
    return "HUNTING_BLOODSMELL";
  case 177:
    return "LOOT_THE_DEAD";
  case 178:
    return "LOOT_TO_REPLACE_MISSING_WEAPON";
  case 179:
    return "HUNT_MY_THIEF";
  case 180:
    return "MAN_THE_GATE";
  case 181:
    return "STRIP_TARGETS_WEAPONS";
  case 182:
    return "PROCESS_AND_STRIP_NEW_SLAVE";
  case 183:
    return "SLAVE_WATCHING";
  case 184:
    return "PUT_LOOT_IN_STORAGE";
  case 185:
    return "CUT_SHACKLES";
  case 186:
    return "BRUTE_FORCE_SHACKLES";
  case 187:
    return "_SLAVE_OBEDIENCE";
  case 188:
    return "WORK_THE_SLAVES";
  case 189:
    return "AUTO_LABOURING_MINES";
  case 190:
    return "AUTO_LABOURING_MINES_PRETEND";
  case 191:
    return "GO_TO_NEAREST_HQ";
  case 192:
    return "GO_TO_SOMEWHERE_FOR_DELIVERING_SLAVES";
  case 193:
    return "CAPTURE_ESCAPING_SLAVES";
  case 194:
    return "GIVE_ALL_MY_SLAVES_TO";
  case 195:
    return "LOCK_ALL_THE_CAGES";
  case 196:
    return "BEAT_CAGE_OCCUPANT";
  case 197:
    return "LOCK_ALL_MY_DOORS_FROM_OUTSIDE";
  case 198:
    return "LOCK_DOOR_FROM_OUTSIDE";
  case 199:
    return "MOVE_TO_BUILDING_DOOR_OUTSIDEPOS";
  case 200:
    return "LEAVE_BUILDING";
  case 201:
    return "PICK_LOCK_ON_SHACKLES";
  case 202:
    return "TOTAL_ESCAPE";
  case 203:
    return "ARREST_TARGET";
  case 204:
    return "HUNT_BOUNTIES";
  case 205:
    return "ARREST_TARGETS_CARRIED_PERSON";
  case 206:
    return "FIND_CAGE_AND_PUT_IN_IF_BOUNTY";
  case 207:
    return "GET_OUT_OF_CAGE_ESCAPE";
  case 208:
    return "GET_OUT_OF_BED_IF_ITS_EMERGENCY";
  case 209:
    return "INVESTIGATE_ALARMS";
  case 210:
    return "INVESTIGATE_ALARMS_ALLIES_ONLY";
  case 211:
    return "POLICE_FREE_PRISONERS_WHEN_DONE";
  case 212:
    return "LOOT_STOLEN_GOODS";
  case 213:
    return "LIFT_PERSON_SNATCHING_ALLOWED";
  case 214:
    return "RELAX_IN_TOWN_PACKAGE";
  case 215:
    return "TRAVEL_TO_TARGET_PACKAGE";
  case 216:
    return "RUN_AROUND_TOWN_LOOKING_FOR_PEOPLE";
  case 217:
    return "GATHER_SLAVES_FROM_CAGES_IF_ITS_AN_EXPORT_TOWN";
  case 218:
    return "GIVE_ALL_MY_SLAVES_TO_IF_ITS_AN_IMPORT_TOWN";
  case 219:
    return "TAKE_OFF_MY_SHACKLES";
  case 220:
    return "EAT_TARGET_ALIVE";
  case 221:
    return "PRETEND_TO_OPERATE_MACHINERY";
  case 222:
    return "MAN_A_TURRET_ON_BUILDING";
  case 223:
    return "PICKUP_INTRUDERS_BUILDING";
  case 224:
    return "TAKE_INTRUDER_OUTSIDE";
  case 225:
    return "LIFT_PERSON_PLAYER_ORDER";
  case 226:
    return "BASH_DOOR_PLAYER_ORDER";
  case 227:
    return "MELEE_ATTACK_ANIMAL";
  case 228:
    return "STEALTH_KNOCKOUT";
  case 229:
    return "STEALTH_KILL";
  case 230:
    return "EAT_A_RANDOM_DEAD_BODY";
  case 231:
    return "EAT_CROPS";
  case 232:
    return "FIND_CROPS_TO_EAT";
  case 233:
    return "EAT_A_RANDOM_KO_BODY";
  case 234:
    return "MAN_A_TURRET_PLAYER_JOB";
  case 235:
    return "SHOOT_AT_TARGET";
  case 236:
    return "WORSHIP_TARGET";
  case 237:
    return "FOGMAN_WORSHIP_VICTIM";
  case 238:
    return "LOOT_ANIMALS_JOB";
  case 239:
    return "GO_HOME_AND_GO_TO_BED_SECURE";
  case 240:
    return "LIFT_PERSON_SNATCHING_ALLOWED_IN_TOWN_ONLY";
  case 241:
    return "LOOT_RESOURCE_ITEMS_WE_HAVE_STORAGE_FOR";
  case 242:
    return "DITCH_ALL_RESOURCES";
  case 243:
    return "AQUIRE_FOOD_AT_HOMEBASE";
  case 244:
    return "GRAB_ONE_FOOD";
  case 245:
    return "GATHER_PRISONERS_FROM_CAGES_IF_FEMALE_OR_BEAST";
  case 246:
    return "KIDNAP_ORDER";
  case 247:
    return "COLLECT_OUTPUT_RESOURCE_BUILD_MATS";
  case 248:
    return "DEFEAT_SQUAD_LIMIT_CHASE_RANGE";
  case 249:
    return "SPLINT_ORDER";
  case 250:
    return "SPLINT_JOB";
  case 251:
    return "ESCAPE_KIDNAP";
  case 252:
    return "ESCAPE_KIDNAP_STR";
  case 253:
    return "FOLLOW_URGENT_ESCAPE";
  case 254:
    return "FINAL_KIDNAPPER_CAGE_JOB";
  case 255:
    return "SIT_ON_THRONE";
  case 256:
    return "GET_OUT_OF_CAGE_OPPORTUNISTIC";
  case 257:
    return "GET_OUT_OF_BED_ONCE_HEALED";
  case 258:
    return "USE_BED_ORDER";
  case 259:
    return "EAT_FOOD_ON_GROUND";
  case 260:
    return "NEW_SLAVE_PROCESSING";
  case 261:
    return "SLEEP_ON_FLOOR_FAKE_AMBUSH";
  case 262:
    return "RANGED_ATTACK";
  case 263:
    return "RANGED_ATTACK_FOCUSED";
  case 264:
    return "EQUIP_CROSSBOW";
  case 265:
    return "UNEQUIP_CROSSBOW";
  case 266:
    return "RANGED_ATTACK_FOCUSED_UNPROVOKED";
  case 267:
    return "MOVE_IN_BOW_RANGE";
  case 268:
    return "STAND_AT_GUARD_NODE_HOMEBUILDING_INDOORS_ONLY";
  case 269:
    return "HEAL_MY_LEGS";
  case 270:
    return "ASSAULT_FORTIFICATIONS_PREFER_GATES";
  case 271:
    return "ASSAULT_FORTIFICATIONS_PREFER_WALLS";
  case 272:
    return "SMASH_BUILDING";
  case 273:
    return "PICKUP_INTRUDERS_TOWN";
  case 274:
    return "TAKE_INTRUDER_OUTSIDE_TOWN";
  case 275:
    return "SIT_AROUND";
  case 276:
    return "LIBERATE_ALL_THE_PRISONERS";
  case 277:
    return "ANIMAL_FETCH_A_LIMB";
  case 278:
    return "PLAY_BECAUSE_I_HAVE_A_LIMB_IN_MOUTH";
  case 279:
    return "CHASE_ALLY_DOGS_WITH_MOUTH_LIMBS";
  case 280:
    return "RUN_AWAY_FORCED";
  case 281:
    return "FIND_CAGE_AND_PUT_DEADGUY_IN";
  case 282:
    return "EAT_A_RANDOM_CAGE_OCCUPANT_MEASURED_RATE";
  case 283:
    return "SHOO_STRANGERS_OUT_OF_MY_BUILDING_IF_PRIVATE";
  case 284:
    return "LOOT_CONTAINER";
  case 285:
    return "CUT_LOCK";
  case 286:
    return "BRUTE_FORCE_LOCK";
  case 287:
    return "BASH_DOOR_HERE";
  case 288:
    return "PROTECT_ALLIES_STAY_IN_TOWN";
  case 289:
    return "STAY_CLOSE_TO_TARGET_ANIMAL";
  case 290:
    return "BASH_GATE_PLAYER_ORDER";
  default:
    std::stringstream ss;
    ss << "TASK_" << type;
    return ss.str();
  }
}
